### ISSUE TITLE
Stuff around Omikron game

### ISSUE THREAD

**Issue by Flemmard** [Chevluh/Omikron_Blender_Importer#2]
Hey,
I've seen your posts on the mayerem forum.
I've been working on some stuff around Omikron, I would love to share it on the forum, but I can't register.
Do you still have contacts there?

Thanks!

**Comment by Chevluh** [comment]
Issues should be purely related to the software itself, I won't be accepting requests like that in the future.
_In the future_, that is. They've reopened registration for a while, although it'll be subject to manual approval, so you should now be able to register.
